language: sh

git:
  clone: false
  
os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - mercurial

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install python3 pip3 mercurial; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python hg; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then wget https://raw.githubusercontent.com/chocolatey/choco/master/src/chocolatey.resources/redirects/RefreshEnv.cmd && cmd.exe //c 'RefreshEnv.cmd' fi

script:
  - python3 --version
  - hg --version
