language: python

os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - mercurial

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install python3 pip3 mercurial; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python hg; fi

script:
  - python3 --version
  - hg --version
